create table if not exists users
(
    id         bigint generated by default as identity,
    email      varchar(255) not null unique,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    password   varchar(255) not null,
    role       varchar(255) not null,
    primary key (id)
);

create table if not exists todos
(
    created_at timestamp(6) not null,
    id         bigint generated by default as identity,
    owner_id   bigint,
    title      varchar(255) not null unique,
    primary key (id),
    foreign key (owner_id) references users
);

create table if not exists todo_collaborator
(
    collaborator_id bigint not null,
    todo_id         bigint not null,
    foreign key (todo_id) references todos,
    foreign key (collaborator_id) references users
);

create table if not exists states
(
    id   bigint generated by default as identity,
    name varchar(255) not null unique,
    primary key (id)
);

create table if not exists tasks
(
    id       bigint generated by default as identity,
    state_id bigint,
    todo_id  bigint,
    name     varchar(255) not null,
    priority varchar(255) check (priority in ('LOW', 'MEDIUM', 'HIGH')),
    primary key (id),
    foreign key (state_id) references states,
    foreign key (todo_id) references todos
);
